In [1]:
# 1.How do you import the NumPy library using an alias
import numpy as np

In [ ]:
#  2.How do you check the version and configuration of NumPy?
np.__version__

'2.0.2'

In [ ]:
np.__config__

<module 'numpy.__config__' from '/usr/local/lib/python3.12/dist-packages/numpy/__config__.py'>

In [ ]:
#  3.How do you create a vector filled with zeros of size 10?
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#  4.How do you find help/documentation for a NumPy function from the command line?
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [ ]:
#  5.How do you create a zero vector of size 10 with the fifth element as 1?
np.array([0,0,0,0,1,0,0,0,0,0])

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
arr=np.zeros(10,dtype=int)
arr[4]=1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
#  6.How do you create a vector with values from 10 to 49?
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#  7.How do you reverse a vector?
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#  8.How do you create a 3x3 matrix with values from 0 to 8?
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#  9.How do you find indices of non-zero elements in an array?
arr=np.array([1,2,4,8,9])
arr[3:5]

array([8, 9])

In [ ]:
#  10.How do you create a 3x3 identity matrix?
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#  11.How do you generate a 3x3x3 array with random values?
np.random.random((3,3,3))

array([[[0.55779797, 0.63103805, 0.83833918],
        [0.355811  , 0.87223349, 0.02891562],
        [0.73753826, 0.04947163, 0.61231543]],

       [[0.02195675, 0.48749929, 0.86059411],
        [0.2225728 , 0.62026648, 0.26548226],
        [0.71375691, 0.46231356, 0.72755075]],

       [[0.26718502, 0.61192336, 0.04403919],
        [0.85440034, 0.14251771, 0.03300306],
        [0.43479491, 0.28999828, 0.31867561]]])

In [ ]:
#  12.How do you find the min and max values in a 10x10 random matrix?
arr=np.random.random((10,10))
print(arr)
print(arr.min())
print(arr.max())

[[0.22119598 0.61798178 0.38989852 0.64043396 0.05994723 0.94057967
  0.39389336 0.63040919 0.97426549 0.87815704]
 [0.61204382 0.90694707 0.30068623 0.74224646 0.70508904 0.83113838
  0.8863969  0.27475581 0.53741862 0.74196325]
 [0.95434905 0.87664865 0.95137698 0.96195004 0.52802694 0.72314302
  0.88040441 0.12454461 0.38097977 0.83708331]
 [0.00548861 0.7689665  0.9704463  0.9568228  0.58863814 0.28185954
  0.92836917 0.22051288 0.44871591 0.10809083]
 [0.57439538 0.71602443 0.45713414 0.92927238 0.85582249 0.91956274
  0.71744317 0.83900302 0.49385094 0.19292589]
 [0.50107697 0.63361278 0.32117277 0.20245577 0.80896001 0.61918945
  0.88688107 0.69444541 0.17089481 0.48466635]
 [0.87980097 0.25980979 0.38670269 0.5305036  0.0799741  0.3109612
  0.99772254 0.25937967 0.62133565 0.33707439]
 [0.88659486 0.44594257 0.576045   0.06993793 0.29936317 0.90879682
  0.03650327 0.84314563 0.54385684 0.01622488]
 [0.11857976 0.82384001 0.07550686 0.03418742 0.95701339 0.36734764
  0.69333719 

In [ ]:
#  13.How do you calculate the mean of a random vector of size 30?
arr=np.random.random(30)
arr.mean()


np.float64(0.5665714885681158)

In [ ]:
#  14.How do you create a 2D array with 1s on the border and 0s inside?
arr=np.ones((3,3),dtype=int)
arr[1,1]=0
arr

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
#  15.What is the result of operations like 0 * np.nan, np.nan == np.nan, etc.?
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [ ]:
#  16.How do you create a matrix with values below the diagonal?
arr=np.arange(1,10).reshape(3,3)
np.tril(arr,k=-1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [ ]:
#  17.How do you create a checkerboard pattern in an 8x8 matrix?
arr=np.zeros((8,8),dtype=int)
arr[1::2,::2]=1
arr[::2,1::2]=0
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
#  18.How do you find the index of a flat element in a 3D shape?
arr = np.arange(24).reshape(2, 3, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
#  19.How do you create a checkerboard pattern using NumPy's tile function?
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
#  20.How do you normalize a matrix (values between 0 and 1)?

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
norm_a = (a - a.min()) / (a.max() - a.min())
print(norm_a)

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [11]:
#  21.How do you define a custom data type for storing color (RGBA)?
d_type=np.dtype([('red',np.uint32),('green',np.uint32),('blue',np.uint32),('alpha',np.float32)])
color=np.array([(100,250,300,500)],dtype=d_type)
color['green']

array([250], dtype=uint32)

In [12]:
#  22.How do you perform a matrix multiplication between two matrices?
arr1=np.arange(4).reshape(2,2)
arr2=np.arange(4,8).reshape(2,2)
np.dot(arr1,arr2)

array([[ 6,  7],
       [26, 31]])

In [14]:
#  23.How do you negate values between two given numbers in a vector?
arr=np.arange(8)
arr[(arr>3) &(arr<6)]*=-4
arr

array([  0,   1,   2,   3, -16, -20,   6,   7])

In [15]:
#  24.What is the output of sum(range(5), -1) vs np.sum(range(5), -1)?
print(sum(range(5), -1)) # -1 is taken as the stating value and it sums up till 4
print(np.sum(range(5), -1)) # -1 is taken as axis here and it sums up the values till 4

9
10


In [17]:
#  25.Which NumPy vector operations are legal or illegal?
#Legal Operations
#Element-wise operations on arrays of the same shape
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)

#Operations with scalars (broadcasting)

a = np.array([1, 2, 3])
print(a + 10)

#Broadcasting with compatible shapes

a = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2,3)
b = np.array([10, 20, 30])  # shape (3,)
print(a + b)



#Comparison & logical operations

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print(a > b)
print(np.logical_and(a>0, b<3))

#Matrix multiplication (dot or @)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a @ b)


#2. Illegal Operations

#Element-wise operations on incompatible shapes

a = np.array([1, 2, 3])  # shape (3,)
b = np.array([10, 20])   # shape (2,)
print(a + b)

#Matrix multiplication with incompatible shapes

a = np.array([[1, 2, 3]])   # shape (1,3)
b = np.array([[4, 5], [6, 7]])  # shape (2,2)
print(a @ b)

[5 7 9]
[ 4 10 18]
[11 12 13]
[[11 22 33]
 [14 25 36]]
[False False  True]
[ True  True  True]
[[19 22]
 [43 50]]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [19]:
#  26.What happens when you divide integers or floats by zero in NumPy?
arr=np.array([1,2,3])
print(arr/0)
arr2=np.array([1.0,2.0,3.0])
print(arr2/0)

[inf inf inf]
[inf inf inf]


/tmp/ipython-input-1782141689.py:3: RuntimeWarning: divide by zero encountered in divide
  print(arr/0)
/tmp/ipython-input-1782141689.py:5: RuntimeWarning: divide by zero encountered in divide
  print(arr2/0)


In [25]:
#  27.How do you round a float array away from zero?
arr=np.array([1.2,2.5,3.6])
np.round(arr)

array([1., 2., 4.])

In [30]:
#  28.How do you extract the integer part of a float using multiple methods?
arr=np.array([1.2,2.5,3.6])
print(arr.astype(int))
print(np.floor(arr))
print(np.trunc(arr))
print(np.fix(arr))
print(np.ceil(arr))


[1 2 3]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]
[2. 3. 4.]
[1.2 2.5 3.6]


In [47]:
#  29.How do you create a 5x5 matrix with row values ranging from 0 to 4?
arr=np.linspace(0,4,25,endpoint=True).reshape(5,5)
arr

array([[0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667],
       [0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ],
       [1.66666667, 1.83333333, 2.        , 2.16666667, 2.33333333],
       [2.5       , 2.66666667, 2.83333333, 3.        , 3.16666667],
       [3.33333333, 3.5       , 3.66666667, 3.83333333, 4.        ]])

In [40]:
#  30.How do you use a generator to create a NumPy array?
gen=(x*x for x in range(5))
print(np.fromiter(gen,dtype=int))
gen=(x*x for x in range(5))
print(np.array(list(gen)))

[ 0  1  4  9 16]
[ 0  1  4  9 16]


In [41]:
# 31.How do you create an array with evenly spaced values between 0 and 1
np.random.random(5)

array([0.98004506, 0.92088912, 0.13530333, 0.57753435, 0.35891551])

In [52]:
# 32.How do you sort a random array?
arr1=np.random.random(5)
print(arr1)
print(np.sort(arr1))


[0.32235388 0.58443178 0.65081438 0.90082012 0.50907231]
[0.32235388 0.50907231 0.58443178 0.65081438 0.90082012]


In [58]:
# 33 How do you sum an array faster than using np.sum?
arr1=np.arange(4)
print(arr1.sum())
print(np.add.reduce(arr1))


6
6


In [59]:
#  34.How do you check if two arrays are equal?
arr1=np.arange(4)
arr2=np.arange(4)
print(np.array_equal(arr1,arr2))
arr3=np.arange(5)
print(np.array_equal(arr1,arr3))


True
False


In [60]:
#  35.How do you make a NumPy array read-only?
arr=np.arange(5)
arr.setflags(write=False)
arr[0]=1

ValueError: assignment destination is read-only

In [61]:
# 36.How do you convert Cartesian coordinates to polar coordinates?
x=np.array([1,0,-1,0])
y=np.array([0,1,0,-1])
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[1. 1. 1. 1.]
[ 0.          1.57079633  3.14159265 -1.57079633]


In [65]:
#  37.How do you replace the maximum value in an array with zero?
arr=np.array([4,6,7,13,9]) #argmax function returns the index of highest element in the array
arr[np.argmax(arr)]=0
arr

array([4, 6, 7, 0, 9])

In [68]:
#  38.How do you create a structured array for (x, y) coordinate pairs?
arr=np.array([(1,2),(4,5)],dtype=[('x','int'),('y','int')])
arr

array([(1, 2), (4, 5)], dtype=[('x', '<i8'), ('y', '<i8')])

In [70]:
#  39.How do you create a Cauchy matrix using two arrays?
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

# To create a Cauchy matrix, we use the formula C_ij = 1 / (x_i - y_j)
# We can use broadcasting to achieve this.
cauchy_matrix = 1.0 / (arr1[:, np.newaxis] - arr2) # 1.0/np.subtract.outer(arr1,aar2) --gives the pairwise differences
cauchy_matrix

array([[-0.33333333, -0.25      , -0.2       ],
       [-0.5       , -0.33333333, -0.25      ],
       [-1.        , -0.5       , -0.33333333]])

In [73]:
#  40.How do you find the range of values for each NumPy scalar type?

# For integer types, use np.iinfo
print("Integer types:")
print(f"int8: Min={np.iinfo(np.int8).min}, Max={np.iinfo(np.int8).max}")
print(f"int32: Min={np.iinfo(np.int32).min}, Max={np.iinfo(np.int32).max}")
print(f"int64: Min={np.iinfo(np.int64).min}, Max={np.iinfo(np.int64).max}")
print(f"uint8: Min={np.iinfo(np.uint8).min}, Max={np.iinfo(np.uint8).max}") # Unsigned integers

print("\nFloating-point types:")
# For floating-point types, use np.finfo
print(f"float32: Min={np.finfo(np.float32).min}, Max={np.finfo(np.float32).max}")
print(f"float64: Min={np.finfo(np.float64).min}, Max={np.finfo(np.float64).max}")

Integer types:
int8: Min=-128, Max=127
int32: Min=-2147483648, Max=2147483647
int64: Min=-9223372036854775808, Max=9223372036854775807
uint8: Min=0, Max=255

Floating-point types:
float32: Min=-3.4028234663852886e+38, Max=3.4028234663852886e+38
float64: Min=-1.7976931348623157e+308, Max=1.7976931348623157e+308


In [79]:
#  41.How do you display all values in a large array?
large_arr=np.arange(10000)
#print(list(large_arr))
np.set_printoptions(threshold=np.inf)
print(large_arr)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

In [85]:
#  42.How do you find the closest value to a given scalar in an array?
arr=np.array([2,4,6,7,1])
scalar=8
diff=np.abs(arr-scalar)
print(diff)
id=np.argmin(diff)
print(id)
print(arr[id])

[6 4 2 1 7]
3
7


In [89]:
#  43.How do you create a structured array with position and color fields?
d_type=[('position',int,2),('color',float,3)]
arr=np.array([((1,3),(3.4,4.5,5.6)),((6,7),(2.3,8.5,4.0))],dtype=d_type)
print(arr['position'])
print(arr['color'])

[[1 3]
 [6 7]]
[[3.4 4.5 5.6]
 [2.3 8.5 4. ]]


In [91]:
#  44.How do you compute pairwise distances between coordinates?

coords1 = np.array([[0, 0], [1, 1], [2, 0]])
coords2 = np.array([[0, 1], [1, 0]])

# To compute pairwise Euclidean distances, we can use broadcasting
# and the sum of squares.
# (x1 - x2)^2 + (y1 - y2)^2

# Expand dimensions for broadcasting
coords1_expanded = coords1[:, np.newaxis, :]  # shape (3, 1, 2)
coords2_expanded = coords2[np.newaxis, :, :]  # shape (1, 2, 2)

# Calculate the difference between coordinates
difference = coords1_expanded - coords2_expanded  # shape (3, 2, 2)

# Square the differences
squared_difference = difference**2  # shape (3, 2, 2)

# Sum the squared differences along the last axis (the coordinate axis)
sum_of_squared_difference = np.sum(squared_difference, axis=-1)  # shape (3, 2)

# Take the square root to get the Euclidean distance
pairwise_distances = np.sqrt(sum_of_squared_difference)

print("Coordinates 1:")
print(coords1)
print("\nCoordinates 2:")
print(coords2)
print("\nPairwise Euclidean distances:")
print(pairwise_distances)

Coordinates 1:
[[0 0]
 [1 1]
 [2 0]]

Coordinates 2:
[[0 1]
 [1 0]]

Pairwise Euclidean distances:
[[1.         1.        ]
 [1.         1.        ]
 [2.23606798 1.        ]]


In [94]:
#  45.How do you cast a float array to integer type in place?
np.array([1.3,2.1,3.5],dtype=int)

array([1, 2, 3])

In [95]:
#  46.How do you read data from a file with missing values?
np.genfromtxt('missing.csv',delimiter=',',filling_values=0)

FileNotFoundError: missing.csv not found.

In [112]:
#  47.How do you iterate through all elements in a NumPy array with indices?
arr1=np.array([(1,2,3,4),(5,6,7,8)])
for index,value in np.ndenumerate(arr1):
    print(index,value)
for index in np.ndindex(arr1.shape):
    print(index,arr1[index])

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [115]:
#  48.How do you create a 2D Gaussian-like array?

# Define the size of the array
size = 5

# Create a meshgrid of coordinates
x, y = np.meshgrid(np.linspace(-1, 1, size), np.linspace(-1, 1, size))

# Calculate the 2D Gaussian function
# The formula for a 2D Gaussian centered at (0, 0) with standard deviation sigma is:
# exp(-(x^2 + y^2) / (2 * sigma^2))
sigma = 0.5
gaussian_array = np.exp(-(x**2 + y**2) / (2 * sigma**2))

print(gaussian_array)

[[0.01831564 0.082085   0.13533528 0.082085   0.01831564]
 [0.082085   0.36787944 0.60653066 0.36787944 0.082085  ]
 [0.13533528 0.60653066 1.         0.60653066 0.13533528]
 [0.082085   0.36787944 0.60653066 0.36787944 0.082085  ]
 [0.01831564 0.082085   0.13533528 0.082085   0.01831564]]


In [117]:
#  49.How do you randomly place a specific number of elements in a 2D array?

rows = 5
cols = 5

# Define the number of elements to randomly place
num_elements_to_place = 10

# Create a 2D array filled with zeros
arr = np.zeros((rows, cols), dtype=int)

# Get all possible indices in the 2D array
all_indices = np.arange(rows * cols)

# Randomly choose 'num_elements_to_place' indices without replacement
random_indices = np.random.choice(all_indices, size=num_elements_to_place, replace=False)

# Convert the flat indices to 2D indices
row_indices, col_indices = np.unravel_index(random_indices, (rows, cols))

# Place a specific value (e.g., 1) at the chosen random indices
arr[row_indices, col_indices] = 1

print(arr)

[[0 1 1 1 0]
 [0 0 0 1 0]
 [1 0 0 1 0]
 [1 1 0 0 1]
 [0 0 1 0 0]]


In [119]:
#  50.How do you subtract the row mean from a matrix?
matrix = np.array([[1, 2, 3], [4, 5, 6]])

row_means = matrix.mean(axis=1, keepdims=True)
result_matrix = matrix - row_means

print("Original matrix:")
print(matrix)
print("\nRow means:")
print(row_means)
print("\nMatrix after subtracting row means:")
print(result_matrix)

Original matrix:
[[1 2 3]
 [4 5 6]]

Row means:
[[2.]
 [5.]]

Matrix after subtracting row means:
[[-1.  0.  1.]
 [-1.  0.  1.]]


In [130]:
#  51.How do you sort a 2D array based on the values of one column?
arr=np.array([(1,9,3),(9,5,6)])
sorted_arr=arr[arr[:,1].argsort()[::-1]]
sorted_arr

array([[1, 9, 3],
       [9, 5, 6]])

In [134]:
#  52.How do you check if a 2D array contains any null (zero-only) columns?
arr=np.array([(0,2,3),(0,5,0)])
print(np.any(np.all(arr==0,axis=0)))

True


In [136]:
#  53.How do you find the nearest value to a given number in a NumPy array?

arr = np.array([10, 23, 15, 30, 8, 25])
given_number = 22

absolute_difference = np.abs(arr - given_number)

nearest_index = np.argmin(absolute_difference)

nearest_value = arr[nearest_index]

print(f"The array is: {arr}")
print(f"The given number is: {given_number}")
print(f"The nearest value in the array to {given_number} is: {nearest_value}")

The array is: [10 23 15 30  8 25]
The given number is: 22
The nearest value in the array to 22 is: 23


In [138]:
#  54.How do you create a NumPy subclass with custom attributes?
class MyArray(np.ndarray):
    def __new__(cls, input_array, custom_attribute):
        obj = np.asarray(input_array).view(cls)
        obj.custom_attribute = custom_attribute
        return obj

In [3]:
#  55.How do you increment elements in an array using an index array with repeats?
arr=np.array([1,2,3,4,5])
indices=np.array([0,1,1,2,2])
np.add.at(arr,indices,1)
print(arr)

[2 4 5 4 5]


In [5]:
#  56.How do you accumulate values into an array based on indices?
arr=np.array([0,0,0,0,0])
indices=np.array([0,1,1,2,3])
values=np.array([1,2,3,4,5])
np.add.at(arr,indices,values)
print(arr)


[1 5 4 5 0]


In [10]:
#  57.How do you count unique colors in a 3D image array?
colors = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]]
])
pixels=colors.reshape(-1,3)
unique_colors=np.unique(pixels,axis=0)
print(unique_colors)
print(len(unique_colors))


[[  0   0 255]
 [  0 255   0]
 [255   0   0]]
3


In [15]:
#  58.How do you compute the sum across the last two axes of a 4D array?
arr=np.random.random((2,3,4,5))
arr.sum(axis=(2,3))


array([[12.90358383, 10.3694851 ,  9.66170352],
       [10.32817839,  9.2729491 , 13.45713702]])

In [16]:
#  59.How do you calculate means of grouped values in an array?
arr=np.array([10,20,30,40,50,60])
groups=np.array([0,0,1,1,2,2])
sum=np.bincount(groups,arr)
count=np.bincount(groups)
print(sum/count)

[15. 35. 55.]


In [18]:
#  60.How do you efficiently get the diagonal of a matrix dot product?
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat_dot=np.dot(arr,arr2)
print("Dot matrix is :",mat_dot)
print("Diagonal of a dot matrix is ", np.diagonal(mat_dot))

Dot matrix is : [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Diagonal of a dot matrix is  [ 30  81 150]


In [19]:
#  61.How do you interleave a vector with a fixed number of zeros?
arr=np.array([1,2,3,4,5])
n=len(arr)
zeroes=2
total_length=n+(n-1)*zeroes
interleaved_arr=np.zeros(total_length,dtype=int)
interleaved_arr[::zeroes+1]=arr
print(interleaved_arr)

[1 0 0 2 0 0 3 0 0 4 0 0 5]


In [21]:
#  62.How do you multiply a (5,5,3) array with a (5,5) array element-wise?
arr1=np.linspace(1,25,75,endpoint=True,dtype=int).reshape(5,5,3)
arr2=np.linspace(1,25,25,endpoint=True,dtype=int).reshape(5,5)
multiplication=arr1*arr2[:,:,np.newaxis]
print(multiplication)

[[[  1   1   1]
  [  2   4   4]
  [  6   9   9]
  [ 12  16  16]
  [ 20  25  25]]

 [[ 30  36  36]
  [ 42  49  49]
  [ 56  64  64]
  [ 72  81  81]
  [ 90 100 100]]

 [[110 121 121]
  [132 144 144]
  [156 169 169]
  [182 182 196]
  [210 210 225]]

 [[240 240 256]
  [272 272 289]
  [306 306 324]
  [342 342 361]
  [380 380 400]]

 [[420 420 441]
  [462 462 484]
  [506 506 529]
  [552 552 576]
  [600 600 625]]]


In [23]:
#  63.How do you swap two rows in a matrix?
arr=np.arange(4).reshape(2,2)
print("Actual array:",arr)
arr[[0,1]]=arr[[1,0]]
print("Swapped array:",arr)

Actual array: [[0 1]
 [2 3]]
Swapped array: [[2 3]
 [0 1]]


In [29]:
#  64.How do you extract unique line segments from triangle definitions?
arr=np.array([
    [0,1,2],
    [1,2,3]]
)
edges=np.vstack([arr[:,[0,1]],
                 arr[:,[1,2]],
                 arr[:,[2,0]]])
sort=np.sort(edges,axis=1)
unique_edges=np.unique(sort,axis=0)
print(unique_edges)

[[0 1]
 [0 2]
 [1 2]
 [1 3]
 [2 3]]


In [31]:
#  65.How do you recreate an array from a bincount?
arr=np.array([0,1,2,2])
counts=np.bincount(arr) #gives how many times the integer value is present in an array
print(counts)
repeated=np.repeat(np.arange(len(counts)),counts) # repeat function takes the length of count as 3 so the elements are 0,1,2 and count tells how many times each value should repeat
print(repeated)

[1 1 2]
[0 1 2 2]


In [32]:
#  66.How do you compute a moving average using a sliding window?
arr=np.array([1,2,3,4,5])
window_size=3
weights=np.ones(window_size)/window_size
moving_average=np.convolve(arr,weights,'valid')
print(moving_average)

[2. 3. 4.]


In [33]:
#  67.How do you create a rolling 2D view from a 1D array?
arr=np.arange(5)
window_sizee=3
rolling_view=np.lib.stride_tricks.sliding_window_view(arr,window_sizee)
print(rolling_view)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [34]:
# 68.How do you invert booleans or negate floats in-place?
arr=np.array([True,False,True])
print(np.logical_not(arr,out=arr))
arr1=np.array([1.0,2.0,3.0])
print(np.negative(arr1,out=arr1))

[False  True False]
[-1. -2. -3.]


In [35]:
#  69.How do you compute the distance from a point to multiple lines?


# Lines defined by two endpoints (N lines)
A = np.array([[0, 0], [1, 1], [2, 0]])   # starting points of lines
B = np.array([[1, 0], [2, 1], [3, 1]])   # ending points of lines

# The point P
P = np.array([1, 2])

# Vector along each line
BA = B - A

# Vector from A to the point P
PA = A - P

# Cross product magnitude (for 2D use determinant)
cross = np.abs(BA[:, 0] * PA[:, 1] - BA[:, 1] * PA[:, 0])

# Distance formula: |cross| / |BA|
distances = cross / np.linalg.norm(BA, axis=1)

print(distances)


[2.         1.         2.12132034]


In [36]:
#  70.How do you compute the distances from multiple points to multiple lines?

# Lines: N lines
A = np.array([[0, 0], [1, 1], [2, 0]])   # start points
B = np.array([[1, 0], [2, 1], [3, 1]])   # end points

# Points: M points
P = np.array([[1, 2], [0, 1], [3, 3]])

# Step 1: Line vectors (shape: N x 2)
BA = B - A  # shape (N, 2)

# Step 2: Reshape points and lines for broadcasting
# P: M x 1 x 2, BA: 1 x N x 2, A: 1 x N x 2
PA = A[np.newaxis, :, :] - P[:, np.newaxis, :]  # shape: M x N x 2
BA = BA[np.newaxis, :, :]                        # shape: 1 x N x 2

# Step 3: Compute 2D cross product magnitude
cross = np.abs(BA[:, :, 0] * PA[:, :, 1] - BA[:, :, 1] * PA[:, :, 0])

# Step 4: Normalize by line length
line_lengths = np.linalg.norm(BA, axis=2)  # shape: 1 x N
distances = cross / line_lengths           # shape: M x N

print(distances)


[[2.         1.         2.12132034]
 [1.         0.         2.12132034]
 [3.         2.         1.41421356]]


In [37]:
 # 71.How do you extract a fixed-shaped subarray centered on a given point?
arr = np.arange(100).reshape(10, 10)

# Center point
center_row, center_col = 5, 5

# Patch size
patch_height, patch_width = 3, 3

# Half sizes
h_half = patch_height // 2
w_half = patch_width // 2

# Compute start and end indices
row_start = max(center_row - h_half, 0)
row_end   = min(center_row + h_half + 1, arr.shape[0])
col_start = max(center_col - w_half, 0)
col_end   = min(center_col + w_half + 1, arr.shape[1])

# Extract patch
patch = arr[row_start:row_end, col_start:col_end]

print("Extracted Patch:\n", patch)


Extracted Patch:
 [[44 45 46]
 [54 55 56]
 [64 65 66]]


In [38]:
#  72.How do you generate overlapping subarrays from a vector?
arr=np.arange(5)
window_sizee=3
rolling_view=np.lib.stride_tricks.sliding_window_view(arr,window_sizee)
print(rolling_view)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [39]:
#  73.How do you compute the rank of a matrix using SVD?
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute SVD
U, S, Vt = np.linalg.svd(A)

# Compute rank
tol = 1e-10
rank = np.sum(S > tol)

print("Singular values:", S)
print("Rank of the matrix:", rank)

Singular values: [1.68481034e+01 1.06836951e+00 4.41842475e-16]
Rank of the matrix: 2


In [41]:
#  74.How do you find the most frequent value in an array?
arr=np.array([1,2,2,3,3,3,4])
value,counts=np.unique(arr,return_counts=True)
index=np.argmax(counts)
print(values[index])

3


In [44]:
#  75.How do you extract all 3x3 contiguous blocks from a 10x10 matrix?
arr=np.arange(100).reshape(10,10)
window_size=(3,3)
blocks=np.lib.stride_tricks.sliding_window_view(arr,window_size)
print(blocks)

[[[[ 0  1  2]
   [10 11 12]
   [20 21 22]]

  [[ 1  2  3]
   [11 12 13]
   [21 22 23]]

  [[ 2  3  4]
   [12 13 14]
   [22 23 24]]

  [[ 3  4  5]
   [13 14 15]
   [23 24 25]]

  [[ 4  5  6]
   [14 15 16]
   [24 25 26]]

  [[ 5  6  7]
   [15 16 17]
   [25 26 27]]

  [[ 6  7  8]
   [16 17 18]
   [26 27 28]]

  [[ 7  8  9]
   [17 18 19]
   [27 28 29]]]


 [[[10 11 12]
   [20 21 22]
   [30 31 32]]

  [[11 12 13]
   [21 22 23]
   [31 32 33]]

  [[12 13 14]
   [22 23 24]
   [32 33 34]]

  [[13 14 15]
   [23 24 25]
   [33 34 35]]

  [[14 15 16]
   [24 25 26]
   [34 35 36]]

  [[15 16 17]
   [25 26 27]
   [35 36 37]]

  [[16 17 18]
   [26 27 28]
   [36 37 38]]

  [[17 18 19]
   [27 28 29]
   [37 38 39]]]


 [[[20 21 22]
   [30 31 32]
   [40 41 42]]

  [[21 22 23]
   [31 32 33]
   [41 42 43]]

  [[22 23 24]
   [32 33 34]
   [42 43 44]]

  [[23 24 25]
   [33 34 35]
   [43 44 45]]

  [[24 25 26]
   [34 35 36]
   [44 45 46]]

  [[25 26 27]
   [35 36 37]
   [45 46 47]]

  [[26 27 28]
   [36 37 38]


In [45]:
#  76.How do you create a 2D symmetric matrix class?
class SymmetricMatrix(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return


In [2]:
#  77.How do you compute the sum of multiple matrix-vector products at once?
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr3 = np.array([[9,10],[11,12]])
vector = np.array([1,2])

# Sum each matrix-vector product
result = arr1 @ vector + arr2 @ vector + arr3 @ vector
print(result)

[51 69]


In [4]:
#  78.How do you compute the sum of blocks in a 2D array?
arr = np.arange(16).reshape(4, 4)
print("Original array:\n", arr)

# Block size
block_size = (2, 2)

# Step 1: Reshape the array into blocks
blocks = arr.reshape(
    arr.shape[0] // block_size[0], block_size[0],
    arr.shape[1] // block_size[1], block_size[1]
)

# Step 2: Sum over the rows and columns inside each block
block_sums = blocks.sum(axis=(1, 3))

print("\nSum of each 2x2 block:\n", block_sums)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Sum of each 2x2 block:
 [[10 18]
 [42 50]]


In [7]:
#  79.How do you simulate the Game of Life using NumPy?

# Grid size
rows, cols = 5, 5
np.random.seed(0)  # for reproducibility

# Initialize random grid (0 = dead, 1 = alive)
grid = np.random.randint(2, size=(rows, cols))
print("Initial Grid:\n", grid)

# Number of generations to simulate
generations = 5

for g in range(generations):
    # Count neighbors using np.roll for 8 directions
    neighbors = (
        np.roll(grid, 1, 0) + np.roll(grid, -1, 0) +  # up, down
        np.roll(grid, 1, 1) + np.roll(grid, -1, 1) +  # left, right
        np.roll(np.roll(grid, 1, 0), 1, 1) +          # up-left
        np.roll(np.roll(grid, 1, 0), -1, 1) +         # up-right
        np.roll(np.roll(grid, -1, 0), 1, 1) +         # down-left
        np.roll(np.roll(grid, -1, 0), -1, 1)          # down-right
    )

    # Apply Game of Life rules
    new_grid = ((grid == 1) & ((neighbors == 2) | (neighbors == 3))) | \
               ((grid == 0) & (neighbors == 3))

    grid = new_grid.astype(int)  # convert boolean to int

    print(f"\nGeneration {g+1}:\n", grid)


Initial Grid:
 [[0 1 1 0 1]
 [1 1 1 1 1]
 [1 0 0 1 0]
 [0 0 0 0 1]
 [0 1 1 0 0]]

Generation 1:
 [[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 1 1 0 0]]

Generation 2:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 0 1 1]
 [0 0 0 0 0]]

Generation 3:
 [[0 0 0 0 0]
 [1 1 1 1 1]
 [0 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]

Generation 4:
 [[0 1 1 0 0]
 [1 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Generation 5:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 0 0 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [6]:
 # 80.How do you extract the top N largest values from an array?
arr = np.array([10, 30, 20, 50, 40])
N = 3

# Sort the array in descending order and take first N values
top_n = np.sort(arr)[-N:][::-1]

print("Top 3 largest values:", top_n)

Top 3 largest values: [50 40 30]


In [7]:
#  81.How do you create a Cartesian product of multiple input arrays?
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

# Create Cartesian product
mesh = np.meshgrid(a, b, c)          # Create coordinate matrices
product = np.array(mesh).T.reshape(-1, 3)

print(product)

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


In [24]:
#  82.How do you create a record array from a regular NumPy array?
data = np.array([['John', 25, 'M'], ['Jane', 30, 'F']], dtype=object)
rec_arr = np._core.records.fromrecords([tuple(row) for row in data], names='name, age, gender',formats='U10,i4,U1')

print(rec_arr)
print(rec_arr.name)   # Access 'name' field
print(rec_arr.age)    # Access 'age' field
print(rec_arr.gender) # Access 'gender' field



[('John', 25, 'M') ('Jane', 30, 'F')]
['John' 'Jane']
[25 30]
['M' 'F']


In [29]:
#  83.How do you raise an array to the power of 3 using different methods?
arr=np.array([1,2,3,4])
print(arr**3)
print(np.power(arr,3))
cube=np.array([x**3 for x in arr])
print(cube)
print(np.multiply(np.multiply(arr,arr),arr))

[ 1  8 27 64]
[ 1  8 27 64]
[ 1  8 27 64]
[ 1  8 27 64]


In [33]:
#  84.How do you find rows in a matrix containing all elements of another matrix?
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[1,3,5]])
print(np.all(np.isin(arr1,arr2),axis=1)) # isin checks if the elements in arr1 are present in arr2, if all(np.all) the elements are present then only it returns true

[ True False]


In [38]:
#  85.How do you filter rows in a matrix with at least one differing value?
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[1,3,5]])
print(np.any(np.not_equal(arr1,arr2),axis=1))

[False  True]


In [43]:
#  86.How do you convert integers to their binary matrix representation?
arr=np.array([1,2,3,4], dtype=np.uint8)
binary_matrix=np.unpackbits(arr[:,np.newaxis],axis=1)
print(binary_matrix)

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]]


In [5]:
#  87.How do you extract unique rows from a 2D array?
import numpy as np


arr=np.array([[1,2,3],[1,2,3],[4,5,6],[6,7,8],[4,5,6]])
unique_rows=np.unique(arr,axis=0)
print(unique_rows)


[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [8]:
#  88.How do you compute inner, outer, sum, and multiplication using einsum?

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.einsum('i,i->',arr1,arr2))
print(np.einsum('i,j->ij',arr1,arr2))
print(np.einsum('i->',arr1))
print(np.einsum('i,i->',arr1,arr2))



32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
6
32


In [9]:
#  89.How do you sample a 2D path at regular intervals?
path = np.array([[0, 0],
                 [1, 2],
                 [3, 3],
                 [6, 1]])
# Differences between consecutive points
diffs = np.diff(path, axis=0)  # shape: (num_points-1, 2)

# Euclidean distance between consecutive points
distances = np.sqrt((diffs**2).sum(axis=1))

# Cumulative distance along the path
cumdist = np.insert(np.cumsum(distances), 0, 0)
num_samples = 10
regular_distances = np.linspace(0, cumdist[-1], num_samples)
x_regular = np.interp(regular_distances, cumdist, path[:, 0])
y_regular = np.interp(regular_distances, cumdist, path[:, 1])

sampled_path = np.stack([x_regular, y_regular], axis=1)
print(sampled_path)

[[0.         0.        ]
 [0.40138351 0.80276701]
 [0.80276701 1.60553402]
 [1.40830103 2.20415052]
 [2.21106804 2.60553402]
 [3.01287021 2.99141986]
 [3.75965265 2.4935649 ]
 [4.5064351  1.99570993]
 [5.25321755 1.49785497]
 [6.         1.        ]]


In [13]:
#  90.How do you filter 2D array rows that sum to a specific number using only integers?
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [1, 1, 1],
                [2, 2, 2]])
target_sum = 6
row_sums = np.sum(arr, axis=1)

# Create a boolean mask where the row sum equals the target sum
mask = row_sums == target_sum

# Use the boolean mask to filter the rows
filtered_rows = arr[mask]

print("Original array:\n", arr)
print(mask)
print("\nRow sums:", row_sums)
print(f"\nRows that sum to {target_sum}:\n", filtered_rows)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 1 1]
 [2 2 2]]
[ True False False False  True]

Row sums: [ 6 15 24  3  6]

Rows that sum to 6:
 [[1 2 3]
 [2 2 2]]


In [14]:
#  91.How do you vertically and horizontally stack two arrays?
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [15]:
#  92.How do you apply a custom function to each element of an array?
arr=np.array([1,2,3,4,5])
def custom_function(x):
    return x*2
result=np.vectorize(custom_function)(arr)
print(result)


[ 2  4  6  8 10]


In [17]:
#  93.How do you remove duplicate rows in a 2D array?
arr=np.array([[1,2,3],[1,2,3],[4,5,6]])
unique_rows=np.unique(arr,axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]]


In [18]:
#  94.How do you filter rows based on a specific column value?
arr=np.array([[1,2,3],[1,2,3],[4,5,6]])
value=2
filtered_rows=arr[arr[:,1]==value]
print(filtered_rows)

[[1 2 3]
 [1 2 3]]


In [22]:
#  95.How do you find column-wise and row-wise minimum/maximum indices?
arr=np.array([[3,2,3],[1,5,6]])
print(np.argmax(arr,axis=0))
print(np.argmax(arr,axis=1))
print(np.argmin(arr,axis=0))
print(np.argmin(arr,axis=1))

[0 1 1]
[0 2]
[1 0 0]
[1 0]


In [23]:
#  96.How do you replace NaN values in an array with the column mean?
arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])
col_mean = np.nanmean(arr, axis=0)
print(col_mean)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
print(arr)

[4.  5.  7.5]
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [25]:
#  97.How do you flatten and sort a 2D array?
arr=np.array([[2,7,8],[1,4,5]])
print(np.sort(arr.flatten()))

[1 2 4 5 7 8]


In [26]:
#  98.How do you calculate the correlation coefficient between two vectors?
arr1=np.array([3,7,1,0,4,9])
arr2=np.array([2,4,6,8,9,5])
print(np.corrcoef(arr1,arr2))


[[ 1.        -0.3354102]
 [-0.3354102  1.       ]]


In [31]:
#  99.How do you extract the top-K values along a specific axis?
arr = np.array([[3, 5, 1],
                [9, 8, 4],
                [2, 7, 6]])
k = 2

# Extract top-K values along axis 1 (rows)
top_k_axis1 = np.sort(arr, axis=1)[:, -k:]
print("Top", k, "values along axis 1:\n", top_k_axis1)

Top 2 values along axis 1:
 [[3 5]
 [8 9]
 [6 7]]


In [33]:
#  100.How do you detect outliers in a dataset using IQR?

data = np.array([10, 12, 14, 15, 18, 20, 22, 25, 90])
Q1 = np.percentile(data, 25)
Q3 = np.percentile(data, 75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = data[(data < lower_bound) | (data > upper_bound)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Outliers:", outliers)

Q1: 14.0
Q3: 22.0
IQR: 8.0
Lower bound: 2.0
Upper bound: 34.0
Outliers: [90]


In [34]:
#  101.How do you perform one-hot encoding using NumPy?
data = np.array([1, 2, 3, 2, 1, 3])
one_hot = np.zeros((data.size, data.max() + 1))
one_hot[np.arange(data.size), data] = 1
print(one_hot)


[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [35]:
#  102.How do you find the shape and number of elements in an array?
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.size)


(2, 3)
6


In [36]:
#  103.How do you reshape an array without changing its data?
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [37]:
#  104.How do you flatten a multi-dimensional array?
arr=np.array([[1,2,3],[4,5,6]])
print(arr.flatten())

[1 2 3 4 5 6]


In [39]:
#  105.How do you get the cumulative sum along an axis?
arr=np.array([1,2,3,4,5])
print(np.cumsum(arr))

[ 1  3  6 10 15]


In [41]:
#  106.How do you compute element-wise maximum/minimum of two arrays?
arr1=np.array([1,2,3,9,5])
arr2=np.array([6,7,8,5,10])
print(np.maximum(arr1,arr2))
print(np.minimum(arr1,arr2))

[ 6  7  8  9 10]
[1 2 3 5 5]


In [42]:
#  107.How do you broadcast arrays with different shapes?
arr1=np.array([1,2,3])
arr2=np.array([[4,5,6],[7,8,9]])
print(arr1+arr2)



[[ 5  7  9]
 [ 8 10 12]]


In [43]:
#  108.How do you transpose a matrix and perform dot products?
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8],[9,10],[11,12]])
print(arr1.T)
print(np.dot(arr1,arr2))


[[1 4]
 [2 5]
 [3 6]]
[[ 58  64]
 [139 154]]


In [45]:
#  109.How do you check for NaN or infinite values in an array?
arr=np.array([1,2,np.nan,np.inf])
print(np.isnan(arr))
print(np.isinf(arr))

[False False  True False]
[False False False  True]


In [46]:
#  110.How do you extract diagonal, upper, and lower triangles from a matrix?
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.diag(arr))
print(np.triu(arr))
print(np.tril(arr))

[1 5 9]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]
